---
title: "Introduction to Python"
aliases:
  - /3daypython
  - /intropython
  - /slowpython
sidebar: intropy
---

**February 26<sup>th</sup>-28<sup>th</sup>, 9:00am - 11:00am Pacific Time each day**

**Description**: Python can be used in many humanities and social sciences workflows, and it is an easy and
fun language to learn. This introductory 3-day, 6-hour course will walk you through the basics of programming
in Python starting at the beginner's level. We will cover the main language features – variables and data
types, conditionals, lists, for/while loops, list comprehensions, dictionaries, writing functions, and working
with external libraries, doing many exercises along the way. In the second part we will take a look at some of
the libraries in more details, including pandas for working with large tables, simple plotting with
matplotlib, and few others.

<!-- Python is a popular language for scientific computing, and great for general-purpose programming as well. This -->
<!-- introductory course will walk you through the basics of programming in Python. We will cover the main language -->
<!-- features – variables and data types, conditionals, lists, for/while loops, list comprehensions, dictionaries, -->
<!-- writing functions, and working with external libraries. -->

**Instructor**: Alex Razoumov (SFU)

**Prerequisites**: None

**Software**: We will be using Python on our training cluster, so no need to install it on your
  computer. However, in the long run you would probably benefit from Python on your computer, so you might
  want to look into this. To access the training cluster, you will need a remote secure shell (SSH) client
  installed on your computer in order to participate in the course exercises. On Windows we recommend [the
  free Home Edition of MobaXterm](https://mobaxterm.mobatek.net/download.html){target="_blank"}. On Mac and
  Linux computers SSH is usually pre-installed (try typing `ssh` in a terminal to make sure it is there).

<!-- - working with external libraries -->
<!-- - add many new exercises -->
<!-- - pandas for working with large tables -->
<!-- - simple plotting with matplotlib -->
<!-- - few others -->
<!-- - cartopy? -->

## Links

- [What format to choose to save your data](/formats){target="_blank"} workshop from November 2022
- YouTube channel [Python Tutorials for Digital
  Humanities](https://www.youtube.com/c/pythontutorialsfordigitalhumanities){target="_blank"} by William
  Mattingly
