project:
  type: website

website:
  title: "Various courses"
  sidebar:
    - title: " "
      style: floating
      search: true
      id: chapel-compact
      contents:
        - text: "Front page"
          href: chapel-compact.qmd
        - section: "PART 1: BASIC LANGUAGE FEATURES"
          contents:
            - text: "Introduction to Chapel"
              href: chapel2/chapel-01-intro.qmd
            - text: "Basic syntax and variables + Julia set description"
              href: chapel2/chapel-02-variables.qmd
            - text: "Ranges and arrays"
              href: chapel2/chapel-03-ranges-and-arrays.qmd
            - text: "Control flow"
              href: chapel2/chapel-04-control-flow.qmd
            - text: "Using command-line arguments"
              href: chapel2/chapel-06-command-line-arguments.qmd
            - text: "Measuring code performance"
              href: chapel2/chapel-07-timing.qmd
            - text: "Writing output"
              href: chapel2/chapel-08-output.qmd
        - section: "PART 2: DATA PARALLELISM"
          contents:
            - text: "Intro to parallel computing"
              href: chapel2/chapel-10-intro-parallel.qmd
            - text: "Single-locale data parallelism"
              href: chapel2/chapel-11-single-locale-data-parallel.qmd
            - text: "Multi-locale Chapel"
              href: chapel2/chapel-13-multi-locale-chapel.qmd
            - text: "Domains and data parallelism"
              href: chapel2/chapel-14-domains-and-data-parallel.qmd
            - text: "Parallel Julia set"
              href: chapel2/chapel-15-distributed-julia-set.qmd
            - text: "Heat transfer solver on distributed domains + heat transfer description"
              href: chapel2/chapel-16-distributed-heat-transfer.qmd
        - section: "PART 3: TASK PARALLELISM (BRIEFLY)"
          contents:
            - text: "Fire-and-forget tasks"
              href: chapel2/chapel-20-fire-and-forget-tasks.qmd
            - text: "Synchronization of tasks"
              href: chapel2/chapel-21-synchronising-tasks.qmd
            - text: "Task-parallelizing the heat transfer solver"
              href: chapel2/chapel-22-task-parallel-heat-transfer.qmd
        - section: "PART 4: GPU COMPUTING WITH CHAPEL"
    - title: " "
      style: floating
      search: true
      id: apptainer
      contents:
        - text: "Front page"
          href: apptainer-menu.qmd
        - text: "What is Apptainer / Singularity"
          href: apptainer1/01-intro.qmd
        - text: "Creating and running container images"
          href: apptainer1/02-build.qmd
        - text: "More on running containers"
          href: apptainer1/03-run.qmd
        - text: "Advanced Apptainer usage"
          href: apptainer1/04-advanced.qmd
    - title: " "
      style: floating
      search: true
      id: julia
      contents:
        - text: "Front page"
          href: julia-menu.qmd
        - section: "PART 1"
          contents:
            - text: "Introduction to Julia language"
              href: julia1/julia-01-intro-language.qmd
            - text: "Intro to parallelism"
              href: julia1/julia-02-intro-parallel.qmd
            - text: "Multi-threading with Base.Threads (slow series)"
              href: julia1/julia-03-threads-slow-series.qmd
            - text: "Multi-threading with ThreadsX (slow series)"
              href: julia1/julia-04-threadsx-slow-series.qmd
            - text: "Parallelizing the Julia set with Base.Threads"
              href: julia1/julia-05-threads-julia-set.qmd
            - text: "Parallelizing the Julia set with ThreadsX"
              href: julia1/julia-06-threadsx-julia-set.qmd
        - section: "PART 2"
          contents:
            - text: "Distributed.jl: basics"
              href: julia1/julia-07-distributed1.qmd
            - text: "Distributed.jl: three scalable versions of the slow series"
              href: julia1/julia-08-distributed2.qmd
            - text: "Persistent storage on workers"
              href: julia1/julia-09-persistent-arrays.qmd
            - text: "DistributedArrays.jl"
              href: julia1/julia-10-distributed-arrays.qmd
            - text: "Parallelizing the Julia set with DistributedArrays"
              href: julia1/julia-11-distributed-julia-set.qmd
            - text: "SharedArrays.jl"
              href: julia1/julia-12-shared-arrays.qmd
        - section: "SUPPLEMENTAL MATERIALS"
          contents:
            - text: "Parallelizing the N-body problem"
              href: julia1/julia-13-nbody.qmd
            - text: "Parallelizing the additive Schwarz method"
              href: julia1/julia-14-asm.qmd
            - text: "Distributed linear algebra in Julia"
              href: julia1/julia-15-linear-algebra.qmd
    - title: " "
      style: floating
      search: true
      id: bash
      contents:
        - text: "Front page"
          href: bash-menu.qmd
        - section: "PART 1"
          contents:
            - text: "Introduction"
              href: bash1/bash-01-intro.qmd
            - text: "Navigating the filesystem"
              href: bash1/bash-02-filesystem.qmd
            - text: "Creating, moving and copying things, and aliases"
              href: bash1/bash-03-creating-moving-copying.qmd
            - text: "Archives and compression"
              href: bash1/bash-04-tar-gzip.qmd
            - text: "Transferring files to/from remote computers"
              href: bash1/bash-05-file-transfer.qmd
            - text: "Wildcards, redirection, pipes"
              href: bash1/bash-06-wildcards-redirection-pipes.qmd
        - section: "PART 2"
          contents:
            - text: "Loops"
              href: bash1/bash-07-loops.qmd
            - text: "Bash scripts and functions, and variables"
              href: bash1/bash-08-scripts-functions.qmd
            - text: "Finding things with `grep` and `find`"
              href: bash1/bash-09-grep-find.qmd
            - text: "Text manipulation"
              href: bash1/bash-10-text-manipulation.qmd
            - text: "Other topics and exercises"
              href: bash1/bash-11-other.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-title: On this page
    toc-depth: 3

execute:
  enabled: false
