project:
  type: website

website:
  title: "Various courses"
  sidebar:
    - title: " "
      style: floating
      search: true
      id: chapel-compact
      contents:
        - text: "Front page"
          href: chapel-compact.qmd
        - text: "PART 1: BASIC LANGUAGE FEATURES"
        - text: "Introduction to Chapel"
          href: chapel2/chapel-01-intro.qmd
        - text: "Basic syntax and variables + Julia set description"
          href: chapel2/chapel-02-variables.qmd
        - text: "Ranges and arrays"
          href: chapel2/chapel-03-ranges-and-arrays.qmd
        - text: "Control flow"
          href: chapel2/chapel-04-control-flow.qmd
        - text: "Using command-line arguments"
          href: chapel2/chapel-06-command-line-arguments.qmd
        - text: "Measuring code performance"
          href: chapel2/chapel-07-timing.qmd
        - text: "Writing output"
          href: chapel2/chapel-08-output.qmd
        - text: "PART 2: DATA PARALLELISM"
        - text: "Intro to parallel computing"
          href: chapel2/chapel-10-intro-parallel.qmd
        - text: "Single-locale data parallelism"
          href: chapel2/chapel-11-single-locale-data-parallel.qmd
        - text: "Multi-locale Chapel"
          href: chapel2/chapel-13-multi-locale-chapel.qmd
        - text: "Domains and data parallelism"
          href: chapel2/chapel-14-domains-and-data-parallel.qmd
        - text: "Parallel Julia set"
          href: chapel2/chapel-15-distributed-julia-set.qmd
        - text: "Heat transfer solver on distributed domains + heat transfer description"
          href: chapel2/chapel-16-distributed-heat-transfer.qmd
        - text: "PART 3: TASK PARALLELISM (BRIEFLY)"
        - text: "Fire-and-forget tasks"
          href: chapel2/chapel-20-fire-and-forget-tasks.qmd
        - text: "Synchronization of tasks"
          href: chapel2/chapel-21-synchronising-tasks.qmd
        - text: "Task-parallelizing the heat transfer solver"
          href: chapel2/chapel-22-task-parallel-heat-transfer.qmd
        - text: "PART 4: GPU COMPUTING WITH CHAPEL"
    - title: " "
      style: floating
      search: true
      id: apptainer
      contents:
        - text: "Front page"
          href: apptainer-menu.qmd
        - text: "What is Apptainer / Singularity"
          href: apptainer1/01-intro.qmd
        - text: "Creating and running container images"
          href: apptainer1/02-build.qmd
        - text: "More on running containers"
          href: apptainer1/03-run.qmd
        - text: "Advanced Apptainer usage"
          href: apptainer1/04-advanced.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-title: On this page
    toc-depth: 3

execute:
  enabled: false
