---
title: "Working with Apptainer containers"
aliases:
  - /apptainer
sidebar: apptainer
---

**November 6th (Part 1) and November 13th (Part 2), 10am–noon Pacific Time**

**Instructor**: Alex Razoumov (SFU)

**Target audience**: general

**Level**: beginner

**Prerequisites**: none
<!-- [Introduction to Compute Canada cloud](../cloud_cloud) course -->

This course is a hands-on introduction to working with Apptainer containers in an HPC environment. Apptainer
(formerly Singularity) is a great tool to create custom Linux environments and run off-the-shelf Docker
containers on an HPC cluster. We will look at creating new container images, modifying existing images and
installing software into them and -- if time permits -- running parallel codes inside a container.

<!-- We will be running Docker inside virtual machines (VMs) in Compute Canada cloud, so you must be familiar -->
<!-- with setting up a blank Ubuntu server in a cloud VM before attending this course. -->

**Software**: All attendees will need a remote secure shell (SSH) client installed on their computer in order
to participate in the course exercises. On Mac and Linux computers SSH is usually pre-installed (try typing
`ssh` in a terminal to make sure it is there). Many versions of Windows also provide an OpenSSH client by
default -- try opening PowerShell and typing `ssh` to see if it is available. If not, then we recommend
installing [the free Home Edition of MobaXterm](https://mobaxterm.mobatek.net/download.html).



## Links

- Alliance's [Apptainer wiki page](https://docs.alliancecan.ca/wiki/Apptainer){target="_blank"}
- Official [Apptainer User Guide](https://apptainer.org/docs/user/latest){target="_blank"}
- Our recent webinars:
  - [Hiding large numbers of files in container overlays](https://training.westdri.ca/tools/virtual#manyFilesInOverlays){target="_blank"} by Alex Razoumov (SFU) recorded on 2023-Jan-17
  - [Apptainer](https://www.youtube.com/watch?v=bpmrfVqBowY){target="_blank"} by Paul Preney (SHARCNET) recorded on
    2022-Apr-06: many best practices and a couple of complete workflows on our clusters using `/localscratch`,
    setting `$APPTAINER_CACHEDIR` and `$APPTAINER_TMPDIR` for best performance, using overlays for storing
    millions of small files
  - [Container-based approach to bioinformatics applications](https://bit.ly/3z3emYw){target="_blank"} by Tannistha
    Nandi (UofCalgary) recorded on 2021-Oct-13
- Some great tutorials:
  - [Containers in HPC](https://pawseysc.github.io/sc19-containers){target="_blank"} from Pawsey Centre
  - [Creating and running software containers with Singularity](https://github.com/ArangoGutierrez/Singularity-tutorial){target="_blank"} by Eduardo Arango-Gutierrez
  - [Singularity & MPI Applications](https://github.com/fasrc/User_Codes/tree/master/Singularity_Containers/MPI_Apps){target="_blank"} from Harvard University
  - [Carpentries incubator tutorial](https://carpentries-incubator.github.io/singularity-introduction){target="_blank"} -- some material in our course was borrowed from this tutorial
