---
title: "Scientific visualization with ParaView"
aliases:
  - /introparaview
  - /vis
format:
  html:
    include-in-header: schemas/paraview-menu-schemas.html
---

**July 17<sup>th</sup>, 9:00am**

**Abstract**: ParaView is an open source, multi-platform data analysis and visualization tool designed to run
on a variety of hardware from individual laptops to large supercomputers. With ParaView, users can
interactively visualize 2D and 3D datasets defined on structured, adaptive and unstructured meshes or
particles, animate these datasets over time, and manipulate them with a variety of filters. ParaView supports
both interactive visualization through a graphical user interface (GUI) and scripted visualization, including
offscreen rendering, and is an easy and enjoyable tool to learn.

In this beginner-friendly workshop, you will learn the fundamentals of ParaView, starting with its interface
and the types of data it can import. We will build increasingly sophisticated visualization pipelines using
filters, then explore ParaView’s Python capabilities by converting GUI actions into scripts, modifying them,
and running them. Next, we will create keyframe animations. Finally, we will cover remote and large-scale
visualization on HPC clusters for situations where downloading data to a local computer is impractical or
impossible. Along the way, we will discuss strategies for optimizing datasets for parallel I/O and the compute
resources needed to process very large datasets.



<!-- Small-scale remote visualization can be accomplished using JupyterHub or Open OnDemand, running either -->
<!-- standalone ParaView or a ParaView client within a remote desktop environment. -->

<!-- For larger-scale interactive visualization, we will run a parallel ParaView server on a cluster for data -->
<!-- processing and rendering, and connect to it from a ParaView client on your computer. This setup enables -->
<!-- interactive visualization of very large (multi-GB and potentially TB-scale) datasets without transferring the -->
<!-- data and without being limited by your local system's memory or CPU/GPU resources. -->

<!-- We will then save the interactive visualization pipeline as a script and run it remotely as a batch job on the -->
<!-- cluster, performing all rendering off-screen (without opening any windows) and writing images to files. -->

<!-- If time permits, we might explore workflows involving time and camera animation. -->








**Instructor**: Alex Razoumov (SFU)

<!-- **Helpers**: Jarno van der Kolk, Julie Faure-Lacroix, Marie-Hélène Burle, Tyson Whitehead -->

## Workshop materials

The slides for this workshop are included into the [main ZIP
file](https://raw.githubusercontent.com/razoumov/publish/refs/heads/master/paraview.zip) (~30 MB), along with
sample datasets and various scripts. The slide deck has two parts: introductory `slides1.pdf` and more
advanced `slides2.pdf`.

<!-- In this workshop we'll be covering mostly introductory topics. -->

<!-- In case of problems, check this [temporary mirror](https://transfer.sh/I7NwUJ/paraview.zip). -->

<!-- Here are [the slides](../slides/HPC_and_Making_Scientific_Animations_in_ParaView.pdf) for Day 2. -->

## Prerequisites

Please install ParaView 6.1.x from <https://www.paraview.org/download>{target="_blank"} on your computer
before the workshop. No prior ParaView experience required.

<!-- ::: {.callout-note} -->
<!-- Although ParaView 6.1 is available, there are some issues with it at least in MacOS, so we'll use 6.0 today. -->
<!-- ::: -->




<!-- ## Shared files (this workshop only) -->

<!-- You can find all files in this [shared -->
<!-- folder](https://nextcloud.computecanada.ca/index.php/s/G8xgMzptHDNB7gS){target="_blank"}. -->

<!-- `particles.mkv` shows the fluid (left), settling (u_z<0, middle) and rising (u_z>0, right) particles. -->

<!-- `aggregates.mkv` shows all aggregates with density > 3400 kg/m3; density shown with both size and colour. -->

<!-- `sorted.mkv` shows all aggregates with 2 (left), 3-5 (centre), and 6-12 (right) constituent particles coloured -->
<!-- by density. -->


<!-- `types.mkv` shows the fluid (left), settling (dID=1, middle) and rising (dID=2, right) particles coloured by -->
<!-- the vertical velocity. -->

<!-- `traj.png` shows the trajectories of 30 randomly selected dID=1 (settling, blue) and dID=2 (rising, red) -->
<!-- particles (not aggregates). `trajectories.py` is the Python script to process and store the trajectories in a -->
<!-- VTK file. -->








## Other materials

- In winter 2026, we ran 18 visualization workshops under the [Winter Visualization
  Series](winterseries){target="_blank"}, covering Matplotlib, Seaborn, Plotly (including Dash), Vega-Altair,
  the Grammar of Graphics in both R and Python, all ParaView topics, VMD, network visualization with Gephi,
  in-situ visualization with Catalyst2, and modern web-based visualization using trame.
- We recorded [~30 visualization webinars](https://training.westdri.ca/tools/visualization){target="_blank"}
  as part of the SFU Research Computing Group's training program.
- AR leads the Digital Research Alliance of Canada [National Visualization
  Team](https://ccvis.netlify.app){target="_blank"}: check out the gallery and past visualization contests.




## Videos

In 2020, we recorded our full-day ParaView workshop and split it into short video clips, which are available
below. If anything is unclear after today's workshop or you would like to revisit the material afterwards,
these videos are still an excellent resource. Please keep in mind, however, that some of this content may now
be outdated.

### Intro

- [Basic concepts (7 min)](https://youtu.be/Zp8XPPtq7VA){target="_blank"}
- [1D/2D plotting (8 min)](https://youtu.be/d5LwPlVwEIQ){target="_blank"}
- [Multi-dimensional sci-vis (11 min)](https://youtu.be/jLwW1HklmVo){target="_blank"}

### File formats and workflows

- [Running ParaView (11 min)](https://youtu.be/FloAMW6niRM){target="_blank"}
- [File formats and reading raw binary (7 min)](https://youtu.be/gcqeOSTXUTQ){target="_blank"}
- [VTK file formats: overview and legacy VTK (13 min)](https://youtu.be/IRuZ4DiiwDs){target="_blank"}
- [VTK file formats: XML VTK (4 min)](https://youtu.be/3iiI7VUrgsM){target="_blank"}
- [Scientific file formats (5 min)](https://youtu.be/_kJZRbPQsBE){target="_blank"}
- [ParaView filters (11 min)](https://youtu.be/u7ui0Y4ysoE){target="_blank"}
- [Store your visualization workflow with a state file (2 min)](https://youtu.be/r7cv1lX0Z4M){target="_blank"}
- [Side-by-side visualization (3 min)](https://youtu.be/YZHSufVi0aA){target="_blank"}
- [Visualizing vectors (6 min)](https://youtu.be/QFlKiCOFHYc){target="_blank"}
- [Creating better streamlines (3 min)](https://youtu.be/C3WS2GajvBg){target="_blank"}
- [Line integral convolution (LIC) (3 min)](https://youtu.be/MqqduE3EnS8){target="_blank"}
- [Reading CSV data (6 min)](https://youtu.be/1yrGH7w0rG4){target="_blank"}
- [Putting your visualization online with ParaView Glance (5 min)](https://youtu.be/TWL2CMKSRaU){target="_blank"}

### Animation and scripting

- [Keyframe animation (11 min)](https://youtu.be/FAuZMhHcPkc){target="_blank"}
- [Other ways to produce animations (3 min)](https://youtu.be/gmatGGBf-08){target="_blank"}
- [Intro to ParaView scripting (16 min)](https://youtu.be/DK-a4sznT5I){target="_blank"}
- [Camera animation with scripting (10 min)](https://youtu.be/pttcyiNJS2Q){target="_blank"}
- [Programmable filter (4 min)](https://youtu.be/UA72FV1x418){target="_blank"}

### Remote visualization

- [Intro to remote visualization (11 min)](https://youtu.be/y1BoQIelm7Q){target="_blank"}
- [Small-scale remote visualization (10 min)](https://youtu.be/X4hItHL5JDA){target="_blank"}
- [Large-scale remote visualization (11 min)](https://youtu.be/-o-r4SS93uU){target="_blank"}
- [Using cluster GPUs for rendering (5 min)](https://youtu.be/FjRhoRhnao4){target="_blank"}

<!-- - [Where to find more information (4 min)](https://youtu.be/3fEYScpOB-E){target="_blank"} -->
