---
title: "Training in Research Computing"
aliases:
  - /list
  - /ls
format: html
css: styles-ls.css
---

The Research Computing Group at Simon Fraser University offers workshops, courses, and webinars in
high-performance research computing for researchers at Canadian post-secondary institutions. We work in
collaboration with other universities from British Columbia, Alberta, Saskatchewan, and Manitoba under the
umbrella of the Digital Research Alliance of Canada.

<!-- **Longer courses are shown in larger font, while shorter workshops and webinars are in smaller font.** -->

<!-- add {}.qmd to list.qmd -->

::: {.cards-container}

<!-- ::: {.wide-card} -->
<!-- :::{.card-body} -->
<!-- ### Topic {.card-title} -->
<!-- - [Long course](link) -->
<!-- <span style="margin-bottom: 0.5rem; display: block;"> </span> -->
<!-- - <span style="font-size: 0.72em;">[Short course](link)</span> -->
<!-- ::: -->
<!-- ::: -->

::: {.wide-card}
:::{.card-body}
### Visualization {.card-title}
- [Scientific visualization with ParaView](introparaview)
- [Intermediate ParaView](intermediateparaview) (rarely used)
- [Winter Series](winterseries)
- Large-scale and remote visualization on HPC clusters
- Scientific visualization with VisIt
- [Plot.ly for scientific visualization](plotly)
- <span style="font-size: 0.85em;">[Programmable Filter / Source in ParaView](programmable)</span>
- <span style="font-size: 0.85em;">[In-situ visualization with ParaView's Catalyst2](catalyst)</span>
- <span style="font-size: 0.85em;">[Modern tools for web visualization](trame)</span>
- <span style="font-size: 0.85em;">[3D graph visualization](graph)</span>
- <span style="font-size: 0.85em;">[Command-line image processing with ImageMagick](imagemagick)</span>
:::
:::

::: {.card}
:::{.card-body}
### Linux command line {.card-title}
<!-- - <span style="font-size: ;"> -->
- [Introduction to Bash command line](bash)
- <span style="font-size: 0.85em;">[Bash scripting for beginners](bashscripting)</span>
- <span style="font-size: 0.85em;">[Lesser known but very useful Bash features](bashfeatures)</span>
- <span style="font-size: 0.85em;">[Answering your Bash questions](bash-questions)</span>
:::
:::

::: {.card}
:::{.card-body}
### High-performance computing (HPC) {.card-title}
- [Introduction to HPC](introhpc)
- [Working with Apptainer containers](apptainer)
- <span style="font-size: 0.85em;">[Introduction to makefiles](make)</span>
- <span style="font-size: 0.85em;">[Intro to HPC for R users](rhpc)</span>
:::
:::

::: {.card}
:::{.card-body}
### Research data management (RDM) {.card-title}
- <span style="font-size: 0.85em;">[Distributed file storage with git-annex](annex)</span>
- <span style="font-size: 0.85em;">[What format to choose to save your data](formats)</span>
- <span style="font-size: 0.85em;">[Managing large hierarchical datasets with PyTables](pytables)</span>
- <span style="font-size: 0.85em;">[Distributed datasets with DataLad](datalad)</span>
- <span style="font-size: 0.85em;">[Collaborate via GitHub on a website](git-rcg)</span>
- <span style="font-size: 0.85em;">[Globus-cli for file transfer](globus)</span>
:::
:::

::: {.card}
:::{.card-body}
### Python {.card-title}
- [Introduction to Python](intropython)
- [Scientific Python](scientificpython)
- [Towards HPC Python](pythonhpc)
- [Distributed computing with Ray](ray)
- <span style="font-size: 0.85em;">[Numba JIT compilation to CUDA kernels](numba-gpu)</span>
- <span style="font-size: 0.85em;">[Running parallel Ray workflows](clusterworkflows)</span>
- <span style="font-size: 0.85em;">[Using libraries from Python](https://wgpages.netlify.app/pythonlibraries)</span>
- <span style="font-size: 0.85em;">[Python basics for humanists](humanitiespython)</span>
- <span style="font-size: 0.85em;">[Introduction to API querying](api)</span>
:::
:::

::: {.card}
:::{.card-body}
### Julia {.card-title}
- [Parallel computing in Julia](julia)
- <span style="font-size: 0.85em;">[High-level parallel stencil computations on CPUs and GPUs in Julia](stencil)</span>
- <span style="font-size: 0.85em;">[Multi-processing in Julia](https://wgpages.netlify.app/distributed)</span>
- <span style="font-size: 0.85em;">[Distributed and shared arrays in Julia](https://wgpages.netlify.app/darrays)</span>
- <span style="font-size: 0.85em;">[Installing Julia on your computer](https://wgpages.netlify.app/julia-installation)</span>
:::
:::

::: {.card}
:::{.card-body}
### Chapel {.card-title}
- [Parallel programming in Chapel](chapel)
- [GPU computing with Chapel](chapel-gpu)
:::
:::

::: {.card}
:::{.card-body}
### Cloud {.card-title}
- <span style="font-size: 0.85em;">[Command-line OpenStack](openstack)</span>
- <span style="font-size: 0.85em;">[From cloud to HPC ... building a GPU-enabled container on Arbutus](cloud2hpc)</span>
:::
:::

::: {.card}
:::{.card-body}
### Machine learning {.card-title}
- [Gen-AI with JAX for simulation data](jax)
:::
:::

:::

<!-- ### maybe -->
<!--     vis/ vis1.md vis2.md -->
<!-- ### never -->
<!--     chapel-original.md chapel1/ driConnect.md nationalJulia-202202.md -->
<!--     introPython-menu.md python1/ # an older course, replaced with 3dayPython-menu.md -->


<!-- :::{layout="[[5, 5, 5, 5], [5, 5, 5, 5]]"} -->
<!-- :::{.card .mb-3} -->
<!-- :::{.card-body} -->
<!-- [AI](/ai/index.qmd){.card-title .stretched-link} -->
<!-- [Deep learning frameworks]{.text-muted} -->
<!-- ::: -->
<!-- ::: -->
<!-- :::{.card .mb-3} -->
<!-- :::{.card-body} -->
<!-- [R](/r/index.qmd){.card-title .stretched-link} -->
<!-- [Statistical programming]{.text-muted} -->
<!-- ::: -->
<!-- ::: -->
<!-- ::: -->
