---
title: "Scientific Python"
aliases:
  - /scientificpython
sidebar: scipy
---

**June 6<sup>th</sup>, 1:30pm–4:30pm Pacific Time**

<!-- 3dayPython-menu.md, python3/ contains an updated version of this material, so might want to update it here -->
<!-- Course materials will be added here shortly before the start of the course. -->
<!-- Register for this course {{<a "link" "here">}}. -->

Building on our [Python level 1 course](https://wgpages.netlify.app/intropython){target="_blank"}, this course
will cover more advanced scientific computing in Python. We will talk about speeding up calculations and
working with mathematical arrays with NumPy, working with dataframes in Pandas and Polars, basic plotting,
working with scientific datasets with xarray, and a few other topics.

**Instructors**: Alex Razoumov

**Prerequisites**: This course assumes some basic knowledge of Python: `for` loops, `if` statements, writing
functions, lists, dictionaries.

**Software**: We will be using Python on our training cluster, so no need to install it on your
  computer. However, in the long run you would probably benefit from Python on your computer, so you might
  want to look into this. To access the training cluster, you will need a remote secure shell (SSH) client
  installed on your computer in order to participate in the course exercises. On Windows we recommend [the
  free Home Edition of MobaXterm](https://mobaxterm.mobatek.net/download.html){target="_blank"}. On Mac and
  Linux computers SSH is usually pre-installed (try typing `ssh` in a terminal to make sure it is there).




<!-- <\!-- {{<nolinktitle>}}Plotting with cartopy (additional material){{</nolinktitle>}} \ -\-> -->
<!-- <\!-- {{<linktitle url="../python2/python-15-cartopy" text="Plotting with cartopy">}} (additional material) \ -\-> -->
